apiVersion: v2
name: ghost
version: 1.1.0
appVersion: "6.10.3"
description: Helm chart for Ghost CMS - professional publishing platform
type: application
keywords:
  - ghost
  - cms
  - blog
  - publishing
home: https://ghost.org
sources:
  - https://github.com/TryGhost/Ghost
maintainers:
  - name: rustam
dependencies:
  - name: mariadb
    version: 0.10.1
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: mariadb.enabled
